**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [13]:
## your code(for different question use different cells)
## Q.1.1
import numpy as np
array0 = np.zeros(10, dtype=int)
print(array0)

[0 0 0 0 0 0 0 0 0 0]


In [14]:
#Q.1.2
np.ones(10, dtype=int)*5


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [15]:
#Q.1.3
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
#Q.1.4
np.random.rand(1, )

array([0.33824549])

In [17]:
#Q.1.5
np.linspace(0, 1, 22)

array([0.        , 0.04761905, 0.0952381 , 0.14285714, 0.19047619,
       0.23809524, 0.28571429, 0.33333333, 0.38095238, 0.42857143,
       0.47619048, 0.52380952, 0.57142857, 0.61904762, 0.66666667,
       0.71428571, 0.76190476, 0.80952381, 0.85714286, 0.9047619 ,
       0.95238095, 1.        ])

In [18]:
#Q.1.6
count = 0
string1 = input("enter any string: ")
vowels = "aeiouAEIOU"
for char in string1:
  if char in vowels:
    count += 1
print("number of vowels in string1 is:",count)

enter any string: TungtUngtuNgtunGTungtUngtuNgtunGTungtUngtuNgtunGSAHUR
number of vowels in string1 is: 14


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [19]:
##your code
#Q.2.1
numbers = np.array([12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48])
even = numbers[numbers%2==0]
print(even)

[ 12  44 102  -8  56  90 -24  48]


In [20]:
#Q.2.2
arrayint = np.random.randint(10, 100, (5,4))
print(arrayint)

[[59 55 90 86]
 [25 49 90 82]
 [69 62 85 37]
 [63 32 89 71]
 [72 92 76 44]]


In [21]:
#Q.2.3
arrayint = np.random.randint(10, 100, (5,4))[0:3, 0:2]
print(arrayint)

[[46 28]
 [41 41]
 [80 67]]


In [22]:
#Q.2.4
array1D = np.random.randint(0 , 100, 20)
array2D = array1D.reshape(4,5)
print(array2D)

[[26 93  0 29 88]
 [70 63 44 77 25]
 [31 21 29  4 84]
 [55 40 21 42 62]]


In [23]:
#Q.2.5
array2D1 = array2D.flatten()
print(array2D1)

[26 93  0 29 88 70 63 44 77 25 31 21 29  4 84 55 40 21 42 62]


In [24]:
#Q.2.6
array2D = array2D1.reshape(4,5)
array1 = array2D #A (4,5) array
array2 = np.random.randint(10, 100, (5,4)) # Creatin a (5,4) array to be compatible for dot product with a (4,5) array
array3 = np.dot(array1, array2)
print(array1)
print(array2)
print(array3)

[[26 93  0 29 88]
 [70 63 44 77 25]
 [31 21 29  4 84]
 [55 40 21 42 62]]
[[27 92 78 89]
 [80 71 99 72]
 [83 38 65 54]
 [91 95 52 72]
 [76 74 43 15]]
[[17469 18262 16527 12418]
 [19489 21750 19636 19061]
 [11672 12041 10202  7385]
 [14962 17276 14465 12863]]


**Q.3**

(i) Check if matrix multiplication is valid

In [25]:
#your code here
import numpy as np
array1 = np.random.randint(10, 100, (4,5))
array2 = np.random.randint(10, 100, (5,4))
rol1,col1 = array1.shape
rol2,col2 = array2.shape
if rol2 == col1:
  print(" Valid Multiplication ")
else:
  print(" Invalid Multiplication ")

 Valid Multiplication 


(ii) Using loops (without using numpy)

In [26]:
#your code here
col1 = 0
rol2 = 0
for count in array1[0]:
  col1 += 1
for count in array2:
  rol2 += 1
if rol2 == col1:
  print(" Valid Multiplication ")
else:
  print(" Invalid Multiplication ")


 Valid Multiplication 


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [27]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [28]:
##Q.4.1
count = 0
X = [1,2,3,4,5]
for i in X:
  count += i
meanX = count/len(X)
print(f" Mean of X is = {meanX}")

 Mean of X is = 3.0


In [29]:
##Q.4.2
count = 0
y = [2,4,5,4,5]
for i in y:
  count += i
meany = count/len(y)
print(f" Mean of y is = {meany}")

 Mean of y is = 4.0


In [30]:
##Q.4.3
count = ([0]*100)
X = [1,2,3,4,5]
y = [2,4,5,4,5]
num = den = 0
for i in range(0,5):
  num += (meanX - X[i])*(meany - y[i])
  den += (meanX - X[i])**2
m = num/den
print(f"Slope is = {m}")

Slope is = 0.6


In [31]:
##Q.4.4
c = meany - m*meanX
print(f"Intercept is = {c}")

Intercept is = 2.2


In [32]:
X = float(input("enter any value for x :"))
y =  m*X + c
print(f"Predicted values are = {y}")

enter any value for x :5
Predicted values are = 5.2


##  Pandas


In [33]:
import pandas as pd
import numpy as np
pd1 = pd.read_csv("/content/performance_dataset.csv")

#backup
pd1.to_csv("/content/performance_dataset_backup.csv")

print(pd1.head(10))#dispalying first 10 rows

pd2 = pd1['hours_studied']#accesing and modifying individual column
print(pd2.head(10))

print(pd1.iloc[9]) # cool feature for reading some part of a file
print(pd1.iloc[0,0])

for i in [(row, col) for row, col in zip(*np.where(pd1.isnull()))]: #null as 10.0
  pd1.iloc[i[0],i[1]] = 10.0
print(pd1.head(1))

pd1 = pd1.drop("part_time_job", axis=1) #dropping a column
print(pd1.head(1))

pd1['no time'] = pd1['music_hours_weekly'] + pd1['hours_studied'] #creating a new column
print(pd1.head(10))



   hours_studied  attendance_percent  parent_education  internet_access  \
0       4.743108           79.781453               3.0              NaN   
1      10.992036           97.666558               3.0              1.0   
2       8.848935           57.950598               2.0              0.0   
3       3.481116           84.636899               0.0              0.0   
4       6.264199           58.081774               1.0              0.0   
5      12.954310           66.696510               3.0              0.0   
6       0.719962           60.457167               2.0              0.0   
7       6.713262           63.990601               1.0              1.0   
8      11.797809           84.437431               3.0              1.0   
9       5.399779           76.552077               2.0              0.0   

   school_type  sports_participation  part_time_job  siblings  \
0          NaN                   1.0            0.0       4.0   
1          0.0                   3.0        

csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).