**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
#Q.1.1
import random
NUM_ELEMENTS = 10
ZERO_VALUE = 0
array_of_zeros = [ZERO_VALUE] * NUM_ELEMENTS
print(array_of_zeros)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
#Q.1.2
import random
NUM_ELEMENTS = 10
ZERO_VALUE = 5
array_of_zeros = [ZERO_VALUE] * NUM_ELEMENTS
print(array_of_zeros)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [3]:
#Q.1.3
import numpy as np
random_matrix_1 = np.random.randint(9, size=(3, 3))
print(random_matrix_1)

[[4 2 2]
 [3 4 1]
 [1 7 2]]


In [ ]:
#Q.1.4
import numpy as np
random_float = np.random.uniform(0,1)
print(random_float)

0.5671251469508098


In [ ]:
#Q.1.5
import numpy as np
linear_array = np.linspace(0, 1, 20)
print(linear_array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
#Q.1.6
s = "I am studying in IIT Kanpur"
vowel_count = sum(1 for letter in s.lower() if letter in 'aeiou')
print(f"The total number of vowels is: {vowel_count}")

The total number of vowels is: 9


**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [1]:
##Q.2.1
numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]
even_numbers = [num for num in numbers if num % 2 == 0]
print(even_numbers)

[12, 44, 102, -8, 56, 90, -24, 48]


In [2]:
#Q.2.2
import numpy as np
array_2d = np.random.randint(10, 101, size=(5, 4))
print(array_2d)


[[35 87 53 68]
 [50 98 78 86]
 [26 73 89 20]
 [20 39 55 52]
 [61 41 78 33]]


In [4]:
#Q.2.3
matrix = random_matrix_1
array1 = matrix[0:3,0:2]
print(array1)

[[4 2]
 [3 4]
 [1 7]]


In [6]:
#Q.2.4
import numpy as np
matrix_4x5 = array_2d.reshape(4, 5)
print(matrix_4x5)

[[35 87 53 68 50]
 [98 78 86 26 73]
 [89 20 20 39 55]
 [52 61 41 78 33]]


In [7]:
#Q.2.5
import numpy as np
array_1d = matrix_4x5.reshape(1,20)
print(array_1d)

[[35 87 53 68 50 98 78 86 26 73 89 20 20 39 55 52 61 41 78 33]]


In [10]:
#Q.2.6
import numpy as np
matrix_A = matrix_4x5
matrix_B = np.random.randint(10, size =(5, 4))
result = matrix_A @ matrix_B
print(matrix_A)
print(matrix_B)
print(result)

[[35 87 53 68 50]
 [98 78 86 26 73]
 [89 20 20 39 55]
 [52 61 41 78 33]]
[[8 7 4 2]
 [7 2 1 4]
 [7 8 3 7]
 [1 1 2 8]
 [8 5 0 2]]
[[1728 1161  522 1433]
 [2542 1921  780 1464]
 [1471 1137  514  820]
 [1472 1057  548 1325]]


**Q.3**

(i) Check if matrix multiplication is valid

In [11]:
rol1,col1 = matrix_A.shape
rol2,col2 = matrix_B.shape
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")

Multiplication is valid


(ii) Using loops (without using numpy)

In [14]:
rol1 = 0
col2 = 0
for ele in matrix_A:
  rol1 += 1
for ele in matrix_B:
  col2 += 1
if col1 == rol2:
  print("Multiplication is valid")
else:
  print("Multiplication is invalid")

Multiplication is valid


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


In [18]:
#mean of X
X = [1, 2, 3, 4, 5]
mean_value_x = sum(X) / len(X)
print(f"Mean = {mean_value_x}")

Mean = 3.0


In [17]:
#mean of Y
Y = [2,4,5,4,5]
mean_value_y = sum(Y) / len(Y)
print(f"Mean = {mean_value_y}")

Mean = 4.0


In [23]:
#slope m
def calculate_slope_ols(x_values, y_values):
    numerator = 0
    denominator = 0
    for x, y in zip(x_values, y_values):
        numerator += (x - mean_value_x) * (y - mean_value_y)
        denominator += (x - mean_value_x) ** 2
    if denominator == 0:
        return 0
    slope = numerator / denominator
    return slope
m = calculate_slope_ols(X, Y)
print(f"Slope = {m}")

Slope = 0.6


In [24]:
#intercept c
intercept_c = mean_value_y - (m * mean_value_x)
print(f"Intercept = {intercept_c}")

Intercept = 2.2


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).

In [31]:
pip install pandas
