**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [11]:
## your code(for different question use different cells)
##like Q.1.
#1
import numpy as np
a=[0]*10
arr=np.array(a)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [12]:
#Q.1.2
b=[5]*10
arr=np.array(b)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [13]:
#Q.1.3
a=np.arange(0,9)
arr=a.reshape(3,3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Q.1.4
a=np.random.rand()
print(a)

0.24715188515562803


In [15]:
#Q.1.5


In [ ]:
#Q.1.6
a=input('enter the string:')
count=0
for i in a:
    b='aeiouAEIOU'
    if i in b:
        count+=1
print('total number of vowels in the string are:',count)

**Q.2**


1.   Extract the even numbers from this array using slicing.

numbers = [12, 7, 44, 19, 102, -8, 33, 56, 77, 90, 121, -24, 48]

2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
##your code
#Q.2.1
import numpy as np
arr=np.array([12,7,44,19,102,-8,33,56,77,90,121,-24,48])
even=arr[arr%2==0]
print(even)


[ 12  44 102  -8  56  90 -24  48]


**Q.3**

In [4]:
#Q.2.2
arr=np.random.randint(11,100,(5,4))
print(arr)

[[46 50 91 27]
 [95 18 61 21]
 [15 85 65 60]
 [47 24 75 94]
 [92 94 13 16]]


In [5]:
#Q.2.3
arr2=arr[0:3,0:2]
print(arr2)

[[46 50]
 [95 18]
 [15 85]]


In [7]:
#Q.2.4
arr3=arr.reshape(4,5)
print(arr3)

[[46 50 91 27 95]
 [18 61 21 15 85]
 [65 60 47 24 75]
 [94 92 94 13 16]]


In [10]:
#Q.2.5
arr4=arr3.reshape(1,20)
print(arr4)

[[46 50 91 27 95 18 61 21 15 85 65 60 47 24 75 94 92 94 13 16]]


(i) Check if matrix multiplication is valid

In [ ]:
#your code here
def multiply(x,y):
    import numpy as np
    a=np.shape(x)
    b=np.shape(y)
    if a[1]==b[0]:
        print('matrix multiplication is valid')
    else:  
        print('matrix multiplication is not valid')
      

a=([[1,2,3],[3,4,5]])
b=([[2,3],[2,4],[2,6]])
multiply(a,b)


matrix multiplication is valid


(ii) Using loops (without using numpy)

In [4]:
#your code here
def multiply(x,y):
    if len(x[0])==len(y):
        print('matrix multiplication is valid')
    else:
        print('matrix multiplication is not valid')


a=([[1,2,3],[3,4,5]])
b=([[2,3],[2,4],[2,6]])
multiply(a,b)

matrix multiplication is valid


**Q.4**
**Linear Regression:-** https://tahera-firdose.medium.com/linear-regression-derivation-of-slope-and-intercept-using-ordinary-least-square-971534ec6b77

(i) Given:

In [ ]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

In [15]:

#Q4.1
X = [1,2,3,4,5]
y = [2,4,5,4,5]
a=sum(X)
mx=a/len(X)
print('mean of X is ',mx)

mean of X is  3.0


In [13]:
#Q4.2
b=sum(y)
my=b/len(y)
print('mean of y is ',my)

mean of y is  4.0


In [16]:
#Q4.3
a=0
b=0
for i in range(len(X)):
    a+=(X[i]-mx)*(y[i]-my)
    b+=(X[i]-mx)**2

slope=a/b
print('slope =',slope)

slope = 0.6


In [17]:
#Q4.4
c=my-slope*mx
print('intercept =',c)

intercept = 2.2


In [19]:
#Q4.5

for i in X:
    Y=slope*i+c
    print(f'predicted value of y for x={i} is',Y)

predicted value of y for x=1 is 2.8000000000000003
predicted value of y for x=2 is 3.4000000000000004
predicted value of y for x=3 is 4.0
predicted value of y for x=4 is 4.6
predicted value of y for x=5 is 5.2


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).